name: Sync Fork

on:
  schedule:
    - cron: '5 5 * * 5'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'main'
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Add remote upstream
      run: |
        git remote get-url upstream || git remote add upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/spring-guides/gs-rest-service.git
    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git merge upstream/main  
        git push origin main  
