name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'main'  # Replace with your default branch if different

    - name: Add remote upstream
      run: |
        git remote get-url upstream || git remote add upstream git@github.com:spring-guides/gs-rest-service.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git merge upstream/main  # Replace with upstream's default branch if different
        git push origin main  # Replace with your default branch if different
